apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flinkman
  namespace: argocd
spec:
  destination:
    namespace: flinkman
    server: https://kubernetes.default.svc
  project: default
  source:
    path: flinktest
    repoURL: git@github.com:naeri99/service-test-repository.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
